##############################################################################
# keylime TPM 2.0 Python Dockerfile
#
# This file is for automatic test running of Keylime and rust-keylime.
# It is not recommended for use beyond testing scenarios.
##############################################################################

FROM fedora:latest
LABEL version="2.0.1" description="Keylime - Python Devel Env"

ENV HOME /root
ENV KEYLIME_HOME ${HOME}/keylime

COPY setup_swtpm.sh /root/

RUN dnf install -y \
    git \
    python3-cryptography \
    python3-m2crypto \
    python3-pip \
    python3-requests \
    python3-setuptools \
    python3-sqlalchemy \
    python3-simplejson \
    python3-tornado \
    python3-yaml \
    python3-zmq \
    systemd \
    tpm2-tools

WORKDIR ${HOME}
RUN git clone https://github.com/keylime/keylime.git && \
cd keylime && \
sed -e 's/127.0.0.1/0.0.0.0/g' keylime.conf > tmp_keylime.conf && \
mv tmp_keylime.conf keylime.conf && \
python3 ${KEYLIME_HOME}/setup.py install && \
pip3 install -r $KEYLIME_HOME/requirements.txt && \
${KEYLIME_HOME}/services/installer.sh

RUN dnf makecache && \
  dnf clean all && \
  rm -rf /var/cache/dnf/*
